In [58]:
import pandas as pd
import numpy as np

In [59]:
data = pd.read_csv("Data.csv", encoding = "latin-1")

In [4]:
data.head()

,TOWN,TOWN_DESC,LOCALITY,LOCALITY_DESC,SLOCALITY,SLOCALITY_DESC,POP_CODE,POP_NAME,SECTION,SECTION_DESC,...,AREATYPE,SHOPPER_TYPE,OWNER_NAME,GPS_COORDINATES,GEOCODE,RURAL,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
0,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004014,AL MACCA BAKERY,1,MARTIN QUARTER,...,2,RG,-,"24.88901459,67.04905551",1,N,1,1,1,4
1,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004129,MUSHTAQ BAKERY,1,MARTIN QUARTER,...,2,RG,AHSAN JAMEEL,"24.89015118,67.04589786",1,N,1,1,1,4
2,T00027,SADDAR,2,BOHRI BAZAR,3,PRESS CLUB,T00027002003092,ABBAS BROTHERS BAKERY & CONFECTIONERY (S,9,SADDAR,...,2,01,-,"24.86038398,67.02951905",1,N,1,1,1,4
3,T00009,SOCIETY,1,BAHADURABAD,1,CHOTTI MARKET,T00009001001010,FAREED'S BAKERY,16,BAHADURABAD,...,2,RG,SHAFIQ,"24.88451887,67.06439404",3,Y,1,1,1,4
4,T00009,SOCIETY,1,BAHADURABAD,3,SHARIFABAD,T00009001003015,CRESENT NIMCO,16,BAHADURABAD,...,2,RG,ABDUL QADIR,"24.88241835,67.06616701",3,Y,1,1,1,4

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355178 entries, 0 to 355177
Data columns (total 37 columns):
TOWN               355178 non-null object
TOWN_DESC          355178 non-null object
LOCALITY           355178 non-null int64
LOCALITY_DESC      355178 non-null object
SLOCALITY          355178 non-null int64
SLOCALITY_DESC     355178 non-null object
POP_CODE           355178 non-null object
POP_NAME           355178 non-null object
SECTION            355178 non-null int64
SECTION_DESC       355178 non-null object
POS_TYPE_CODE      355178 non-null int64
POS_TYPE           355178 non-null object
DOC_DATE           355178 non-null object
DOC_NO             355178 non-null int64
ORDER_STATUS       355178 non-null int64
PJP                355178 non-null int64
REF_PJP            355177 non-null float64
DSR                355178 non-null int64
REF_DSR            355177 non-null float64
HHT_SRNO           354757 non-null float64
USER_ENTRY         355178 non-null object
PAYMENT_MODE       354664 non-null float64
MARKET_NAME        355178 non-null object
STREET             354951 non-null object
COMPANY_RANK       355178 non-null int64
RANK               355178 non-null int64
ACTIVE             355178 non-null int64
AREATYPE           355178 non-null int64
SHOPPER_TYPE       350022 non-null object
OWNER_NAME         355178 non-null object
GPS_COORDINATES    304869 non-null object
GEOCODE            355178 non-null int64
RURAL              355178 non-null object
SUB_ELEMENT        355178 non-null int64
CHANNEL            355178 non-null int64
SUB_CHANNEL        355178 non-null int64
ELEMENT            355178 non-null int64
dtypes: float64(4), int64(17), object(16)
memory usage: 78.6+ MB

In [6]:
data.describe()

,LOCALITY,SLOCALITY,SECTION,POS_TYPE_CODE,DOC_NO,ORDER_STATUS,PJP,REF_PJP,DSR,REF_DSR,...,PAYMENT_MODE,COMPANY_RANK,RANK,ACTIVE,AREATYPE,GEOCODE,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
count,355178.000000,355178.000000,355178.000000,355178.000000,3.551780e+05,355178.000000,355178.000000,355177.000000,355178.000000,355177.000000,...,354664.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000
mean,2.869820,2.115193,25.587900,5.513168,1.516422e+11,0.442381,9.341829,1125.131388,9.358080,105.492898,...,1.050972,1.462585,3.115981,0.744908,1.999665,1.518974,5.513168,1.040979,1.427304,2.320544
std,1.442698,1.157632,16.175905,3.328402,1.366982e+10,0.496670,9.023358,323.627075,6.936887,4.926169,...,0.219941,2.977828,0.413137,0.435913,0.018301,0.876707,3.328402,0.216452,1.020330,0.852102
min,1.000000,1.000000,1.000000,1.000000,1.000091e+06,0.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,3.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,1.000000,10.000000,4.000000,1.400120e+11,0.000000,2.000000,1002.000000,2.000000,102.000000,...,1.000000,1.000000,3.000000,0.000000,2.000000,1.000000,4.000000,1.000000,1.000000,2.000000
50%,3.000000,2.000000,30.000000,4.000000,1.500121e+11,0.000000,11.000000,1005.000000,11.000000,104.000000,...,1.000000,1.000000,3.000000,1.000000,2.000000,1.000000,4.000000,1.000000,1.000000,2.000000
75%,4.000000,3.000000,41.000000,7.000000,1.600181e+11,1.000000,13.000000,1013.000000,13.000000,106.000000,...,1.000000,1.000000,3.000000,1.000000,2.000000,3.000000,7.000000,1.000000,1.000000,3.000000
max,8.000000,7.000000,54.000000,20.000000,1.720010e+11,1.000000,2001.000000,2007.000000,26.000000,121.000000,...,2.000000,21.000000,7.000000,1.000000,2.000000,3.000000,20.000000,3.000000,4.000000,5.000000

In [7]:
print(data.shape)

(355178, 37)

In [8]:
data.count()

TOWN               355178
TOWN_DESC          355178
LOCALITY           355178
LOCALITY_DESC      355178
SLOCALITY          355178
SLOCALITY_DESC     355178
POP_CODE           355178
POP_NAME           355178
SECTION            355178
SECTION_DESC       355178
POS_TYPE_CODE      355178
POS_TYPE           355178
DOC_DATE           355178
DOC_NO             355178
ORDER_STATUS       355178
PJP                355178
REF_PJP            355177
DSR                355178
REF_DSR            355177
HHT_SRNO           354757
USER_ENTRY         355178
PAYMENT_MODE       354664
MARKET_NAME        355178
STREET             354951
COMPANY_RANK       355178
RANK               355178
ACTIVE             355178
AREATYPE           355178
SHOPPER_TYPE       350022
OWNER_NAME         355178
GPS_COORDINATES    304869
GEOCODE            355178
RURAL              355178
SUB_ELEMENT        355178
CHANNEL            355178
SUB_CHANNEL        355178
ELEMENT            355178
dtype: int64

In [60]:
data[['GPS_COORDINATES']] = data[['GPS_COORDINATES']].fillna(value = '0.0,0.0')

In [61]:
pd.set_option('display.max_columns', None)

In [62]:
data[['STREET']] = data[['STREET']].fillna(value = 'N/A')

In [63]:
data.head()

,TOWN,TOWN_DESC,LOCALITY,LOCALITY_DESC,SLOCALITY,SLOCALITY_DESC,POP_CODE,POP_NAME,SECTION,SECTION_DESC,POS_TYPE_CODE,POS_TYPE,DOC_DATE,DOC_NO,ORDER_STATUS,PJP,REF_PJP,DSR,REF_DSR,HHT_SRNO,USER_ENTRY,PAYMENT_MODE,MARKET_NAME,STREET,COMPANY_RANK,RANK,ACTIVE,AREATYPE,SHOPPER_TYPE,OWNER_NAME,GPS_COORDINATES,GEOCODE,RURAL,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
0,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004014,AL MACCA BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080881,0,22,1013.0,21,104.0,6.0,021,2.0,SHOP NO 1 F-173/4,USMANIA MASJID,1,3,1,2,RG,-,"24.88901459,67.04905551",1,N,1,1,1,4
1,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004129,MUSHTAQ BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080941,1,22,1013.0,21,104.0,9.0,021,2.0,MARTIN ROAD JAMSHEED ROAD,BAKADI MASJID,1,3,1,2,RG,AHSAN JAMEEL,"24.89015118,67.04589786",1,N,1,1,1,4
2,T00027,SADDAR,2,BOHRI BAZAR,3,PRESS CLUB,T00027002003092,ABBAS BROTHERS BAKERY & CONFECTIONERY (S,9,SADDAR,1,Bakery,2017-10-03 00:00:00.000,170020078691,1,20,2004.0,20,117.0,20.0,020,2.0,-,PRESS CLUB,21,3,1,2,01,-,"24.86038398,67.02951905",1,N,1,1,1,4
3,T00009,SOCIETY,1,BAHADURABAD,1,CHOTTI MARKET,T00009001001010,FAREED'S BAKERY,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039501,1,12,2003.0,12,115.0,21.0,laraib,1.0,SHARFABAD CHOWK SHOP NO 7,C.P BERAN MASJID,1,3,1,2,RG,SHAFIQ,"24.88451887,67.06439404",3,Y,1,1,1,4
4,T00009,SOCIETY,1,BAHADURABAD,3,SHARIFABAD,T00009001003015,CRESENT NIMCO,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039471,0,12,2003.0,12,115.0,25.0,laraib,1.0,SHOP NO 20 RASHEEDABAD,KOKAN GROUND,1,3,1,2,RG,ABDUL QADIR,"24.88241835,67.06616701",3,Y,1,1,1,4

In [64]:
data[['SHOPPER_TYPE']] = data[['SHOPPER_TYPE']].fillna(value = '01')

In [65]:
data.head()

,TOWN,TOWN_DESC,LOCALITY,LOCALITY_DESC,SLOCALITY,SLOCALITY_DESC,POP_CODE,POP_NAME,SECTION,SECTION_DESC,POS_TYPE_CODE,POS_TYPE,DOC_DATE,DOC_NO,ORDER_STATUS,PJP,REF_PJP,DSR,REF_DSR,HHT_SRNO,USER_ENTRY,PAYMENT_MODE,MARKET_NAME,STREET,COMPANY_RANK,RANK,ACTIVE,AREATYPE,SHOPPER_TYPE,OWNER_NAME,GPS_COORDINATES,GEOCODE,RURAL,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
0,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004014,AL MACCA BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080881,0,22,1013.0,21,104.0,6.0,021,2.0,SHOP NO 1 F-173/4,USMANIA MASJID,1,3,1,2,RG,-,"24.88901459,67.04905551",1,N,1,1,1,4
1,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004129,MUSHTAQ BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080941,1,22,1013.0,21,104.0,9.0,021,2.0,MARTIN ROAD JAMSHEED ROAD,BAKADI MASJID,1,3,1,2,RG,AHSAN JAMEEL,"24.89015118,67.04589786",1,N,1,1,1,4
2,T00027,SADDAR,2,BOHRI BAZAR,3,PRESS CLUB,T00027002003092,ABBAS BROTHERS BAKERY & CONFECTIONERY (S,9,SADDAR,1,Bakery,2017-10-03 00:00:00.000,170020078691,1,20,2004.0,20,117.0,20.0,020,2.0,-,PRESS CLUB,21,3,1,2,01,-,"24.86038398,67.02951905",1,N,1,1,1,4
3,T00009,SOCIETY,1,BAHADURABAD,1,CHOTTI MARKET,T00009001001010,FAREED'S BAKERY,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039501,1,12,2003.0,12,115.0,21.0,laraib,1.0,SHARFABAD CHOWK SHOP NO 7,C.P BERAN MASJID,1,3,1,2,RG,SHAFIQ,"24.88451887,67.06439404",3,Y,1,1,1,4
4,T00009,SOCIETY,1,BAHADURABAD,3,SHARIFABAD,T00009001003015,CRESENT NIMCO,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039471,0,12,2003.0,12,115.0,25.0,laraib,1.0,SHOP NO 20 RASHEEDABAD,KOKAN GROUND,1,3,1,2,RG,ABDUL QADIR,"24.88241835,67.06616701",3,Y,1,1,1,4

In [66]:
data.count()

TOWN               355178
TOWN_DESC          355178
LOCALITY           355178
LOCALITY_DESC      355178
SLOCALITY          355178
SLOCALITY_DESC     355178
POP_CODE           355178
POP_NAME           355178
SECTION            355178
SECTION_DESC       355178
POS_TYPE_CODE      355178
POS_TYPE           355178
DOC_DATE           355178
DOC_NO             355178
ORDER_STATUS       355178
PJP                355178
REF_PJP            355177
DSR                355178
REF_DSR            355177
HHT_SRNO           354757
USER_ENTRY         355178
PAYMENT_MODE       354664
MARKET_NAME        355178
STREET             355178
COMPANY_RANK       355178
RANK               355178
ACTIVE             355178
AREATYPE           355178
SHOPPER_TYPE       355178
OWNER_NAME         355178
GPS_COORDINATES    355178
GEOCODE            355178
RURAL              355178
SUB_ELEMENT        355178
CHANNEL            355178
SUB_CHANNEL        355178
ELEMENT            355178
dtype: int64

In [67]:
data[['REF_PJP']] = data[['REF_PJP']].fillna(value = '1007')

In [68]:
data.columns

Index(['TOWN', 'TOWN_DESC', 'LOCALITY', 'LOCALITY_DESC', 'SLOCALITY',
       'SLOCALITY_DESC', 'POP_CODE', 'POP_NAME', 'SECTION', 'SECTION_DESC',
       'POS_TYPE_CODE', 'POS_TYPE', 'DOC_DATE', 'DOC_NO', 'ORDER_STATUS',
       'PJP', 'REF_PJP', 'DSR', 'REF_DSR', 'HHT_SRNO', 'USER_ENTRY',
       'PAYMENT_MODE', 'MARKET_NAME', 'STREET', 'COMPANY_RANK', 'RANK',
       'ACTIVE', 'AREATYPE', 'SHOPPER_TYPE', 'OWNER_NAME', 'GPS_COORDINATES',
       'GEOCODE', 'RURAL', 'SUB_ELEMENT', 'CHANNEL', 'SUB_CHANNEL', 'ELEMENT'],
      dtype='object')

In [69]:
data[['HHT_SRNO']] = data[['HHT_SRNO']].fillna(value = '0')

In [70]:
data.count()

TOWN               355178
TOWN_DESC          355178
LOCALITY           355178
LOCALITY_DESC      355178
SLOCALITY          355178
SLOCALITY_DESC     355178
POP_CODE           355178
POP_NAME           355178
SECTION            355178
SECTION_DESC       355178
POS_TYPE_CODE      355178
POS_TYPE           355178
DOC_DATE           355178
DOC_NO             355178
ORDER_STATUS       355178
PJP                355178
REF_PJP            355178
DSR                355178
REF_DSR            355177
HHT_SRNO           355178
USER_ENTRY         355178
PAYMENT_MODE       354664
MARKET_NAME        355178
STREET             355178
COMPANY_RANK       355178
RANK               355178
ACTIVE             355178
AREATYPE           355178
SHOPPER_TYPE       355178
OWNER_NAME         355178
GPS_COORDINATES    355178
GEOCODE            355178
RURAL              355178
SUB_ELEMENT        355178
CHANNEL            355178
SUB_CHANNEL        355178
ELEMENT            355178
dtype: int64

In [71]:
data[['REF_DSR']] = data[['REF_DSR']].fillna(value = '107')

In [72]:
pd.set_option('display.max_columns', None)

In [73]:
data.head()

,TOWN,TOWN_DESC,LOCALITY,LOCALITY_DESC,SLOCALITY,SLOCALITY_DESC,POP_CODE,POP_NAME,SECTION,SECTION_DESC,POS_TYPE_CODE,POS_TYPE,DOC_DATE,DOC_NO,ORDER_STATUS,PJP,REF_PJP,DSR,REF_DSR,HHT_SRNO,USER_ENTRY,PAYMENT_MODE,MARKET_NAME,STREET,COMPANY_RANK,RANK,ACTIVE,AREATYPE,SHOPPER_TYPE,OWNER_NAME,GPS_COORDINATES,GEOCODE,RURAL,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
0,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004014,AL MACCA BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080881,0,22,1013,21,104,6,021,2.0,SHOP NO 1 F-173/4,USMANIA MASJID,1,3,1,2,RG,-,"24.88901459,67.04905551",1,N,1,1,1,4
1,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004129,MUSHTAQ BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080941,1,22,1013,21,104,9,021,2.0,MARTIN ROAD JAMSHEED ROAD,BAKADI MASJID,1,3,1,2,RG,AHSAN JAMEEL,"24.89015118,67.04589786",1,N,1,1,1,4
2,T00027,SADDAR,2,BOHRI BAZAR,3,PRESS CLUB,T00027002003092,ABBAS BROTHERS BAKERY & CONFECTIONERY (S,9,SADDAR,1,Bakery,2017-10-03 00:00:00.000,170020078691,1,20,2004,20,117,20,020,2.0,-,PRESS CLUB,21,3,1,2,01,-,"24.86038398,67.02951905",1,N,1,1,1,4
3,T00009,SOCIETY,1,BAHADURABAD,1,CHOTTI MARKET,T00009001001010,FAREED'S BAKERY,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039501,1,12,2003,12,115,21,laraib,1.0,SHARFABAD CHOWK SHOP NO 7,C.P BERAN MASJID,1,3,1,2,RG,SHAFIQ,"24.88451887,67.06439404",3,Y,1,1,1,4
4,T00009,SOCIETY,1,BAHADURABAD,3,SHARIFABAD,T00009001003015,CRESENT NIMCO,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039471,0,12,2003,12,115,25,laraib,1.0,SHOP NO 20 RASHEEDABAD,KOKAN GROUND,1,3,1,2,RG,ABDUL QADIR,"24.88241835,67.06616701",3,Y,1,1,1,4

In [74]:
data.count()

TOWN               355178
TOWN_DESC          355178
LOCALITY           355178
LOCALITY_DESC      355178
SLOCALITY          355178
SLOCALITY_DESC     355178
POP_CODE           355178
POP_NAME           355178
SECTION            355178
SECTION_DESC       355178
POS_TYPE_CODE      355178
POS_TYPE           355178
DOC_DATE           355178
DOC_NO             355178
ORDER_STATUS       355178
PJP                355178
REF_PJP            355178
DSR                355178
REF_DSR            355178
HHT_SRNO           355178
USER_ENTRY         355178
PAYMENT_MODE       354664
MARKET_NAME        355178
STREET             355178
COMPANY_RANK       355178
RANK               355178
ACTIVE             355178
AREATYPE           355178
SHOPPER_TYPE       355178
OWNER_NAME         355178
GPS_COORDINATES    355178
GEOCODE            355178
RURAL              355178
SUB_ELEMENT        355178
CHANNEL            355178
SUB_CHANNEL        355178
ELEMENT            355178
dtype: int64

In [75]:
data['STREET'] = data['STREET'].replace(['-'], 'N/A')

In [76]:
data['MARKET_NAME'] = data['MARKET_NAME'].replace(['-'], 'N/A')

In [77]:
data.head()

,TOWN,TOWN_DESC,LOCALITY,LOCALITY_DESC,SLOCALITY,SLOCALITY_DESC,POP_CODE,POP_NAME,SECTION,SECTION_DESC,POS_TYPE_CODE,POS_TYPE,DOC_DATE,DOC_NO,ORDER_STATUS,PJP,REF_PJP,DSR,REF_DSR,HHT_SRNO,USER_ENTRY,PAYMENT_MODE,MARKET_NAME,STREET,COMPANY_RANK,RANK,ACTIVE,AREATYPE,SHOPPER_TYPE,OWNER_NAME,GPS_COORDINATES,GEOCODE,RURAL,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
0,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004014,AL MACCA BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080881,0,22,1013,21,104,6,021,2.0,SHOP NO 1 F-173/4,USMANIA MASJID,1,3,1,2,RG,-,"24.88901459,67.04905551",1,N,1,1,1,4
1,T00026,PIB COLONY,1,JAMSHEED ROAD,4,MARTIN QUARTER,T00026001004129,MUSHTAQ BAKERY,1,MARTIN QUARTER,1,Bakery,2017-10-03 00:00:00.000,170022080941,1,22,1013,21,104,9,021,2.0,MARTIN ROAD JAMSHEED ROAD,BAKADI MASJID,1,3,1,2,RG,AHSAN JAMEEL,"24.89015118,67.04589786",1,N,1,1,1,4
2,T00027,SADDAR,2,BOHRI BAZAR,3,PRESS CLUB,T00027002003092,ABBAS BROTHERS BAKERY & CONFECTIONERY (S,9,SADDAR,1,Bakery,2017-10-03 00:00:00.000,170020078691,1,20,2004,20,117,20,020,2.0,N/A,PRESS CLUB,21,3,1,2,01,-,"24.86038398,67.02951905",1,N,1,1,1,4
3,T00009,SOCIETY,1,BAHADURABAD,1,CHOTTI MARKET,T00009001001010,FAREED'S BAKERY,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039501,1,12,2003,12,115,21,laraib,1.0,SHARFABAD CHOWK SHOP NO 7,C.P BERAN MASJID,1,3,1,2,RG,SHAFIQ,"24.88451887,67.06439404",3,Y,1,1,1,4
4,T00009,SOCIETY,1,BAHADURABAD,3,SHARIFABAD,T00009001003015,CRESENT NIMCO,16,BAHADURABAD,1,Bakery,2017-10-03 00:00:00.000,170012039471,0,12,2003,12,115,25,laraib,1.0,SHOP NO 20 RASHEEDABAD,KOKAN GROUND,1,3,1,2,RG,ABDUL QADIR,"24.88241835,67.06616701",3,Y,1,1,1,4

In [78]:
data.PAYMENT_MODE.value_counts(dropna=False).head()

 1.0    336586
 2.0     18078
NaN        514
Name: PAYMENT_MODE, dtype: int64

In [79]:
data.SHOPPER_TYPE.value_counts(dropna=False).head()

RG    241177
01    113638
L1       363
Name: SHOPPER_TYPE, dtype: int64

In [80]:
data.describe()

,LOCALITY,SLOCALITY,SECTION,POS_TYPE_CODE,DOC_NO,ORDER_STATUS,PJP,DSR,PAYMENT_MODE,COMPANY_RANK,RANK,ACTIVE,AREATYPE,GEOCODE,SUB_ELEMENT,CHANNEL,SUB_CHANNEL,ELEMENT
count,355178.000000,355178.000000,355178.000000,355178.000000,3.551780e+05,355178.000000,355178.000000,355178.000000,354664.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000,355178.000000
mean,2.869820,2.115193,25.587900,5.513168,1.516422e+11,0.442381,9.341829,9.358080,1.050972,1.462585,3.115981,0.744908,1.999665,1.518974,5.513168,1.040979,1.427304,2.320544
std,1.442698,1.157632,16.175905,3.328402,1.366982e+10,0.496670,9.023358,6.936887,0.219941,2.977828,0.413137,0.435913,0.018301,0.876707,3.328402,0.216452,1.020330,0.852102
min,1.000000,1.000000,1.000000,1.000000,1.000091e+06,0.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,1.000000,10.000000,4.000000,1.400120e+11,0.000000,2.000000,2.000000,1.000000,1.000000,3.000000,0.000000,2.000000,1.000000,4.000000,1.000000,1.000000,2.000000
50%,3.000000,2.000000,30.000000,4.000000,1.500121e+11,0.000000,11.000000,11.000000,1.000000,1.000000,3.000000,1.000000,2.000000,1.000000,4.000000,1.000000,1.000000,2.000000
75%,4.000000,3.000000,41.000000,7.000000,1.600181e+11,1.000000,13.000000,13.000000,1.000000,1.000000,3.000000,1.000000,2.000000,3.000000,7.000000,1.000000,1.000000,3.000000
max,8.000000,7.000000,54.000000,20.000000,1.720010e+11,1.000000,2001.000000,26.000000,2.000000,21.000000,7.000000,1.000000,2.000000,3.000000,20.000000,3.000000,4.000000,5.000000

In [104]:
print (data.dtypes)

TOWN                       object
TOWN_DESC                  object
LOCALITY                    int64
LOCALITY_DESC              object
SLOCALITY                   int64
SLOCALITY_DESC             object
POP_CODE                   object
POP_NAME                   object
SECTION                     int64
SECTION_DESC               object
POS_TYPE_CODE               int64
POS_TYPE                   object
DOC_DATE           datetime64[ns]
DOC_NO                      int64
ORDER_STATUS             category
PJP                         int64
REF_PJP                     int64
DSR                         int64
REF_DSR                     int64
HHT_SRNO                    int64
USER_ENTRY                 object
PAYMENT_MODE             category
MARKET_NAME                object
STREET                     object
COMPANY_RANK                int64
RANK                        int64
ACTIVE                   category
AREATYPE                 category
SHOPPER_TYPE             category
OWNER_NAME                 object
GPS_COORDINATES            object
GEOCODE                     int64
RURAL                    category
SUB_ELEMENT              category
CHANNEL                  category
SUB_CHANNEL              category
ELEMENT                  category
dtype: object

In [86]:
data.REF_PJP = data.REF_PJP.astype('int64')

In [87]:
data.HHT_SRNO = data.HHT_SRNO.astype('int64')

In [88]:
data.REF_DSR = data.REF_DSR.astype('int64')

In [90]:
data.PAYMENT_MODE = data.PAYMENT_MODE.astype('category')

In [91]:
data.AREATYPE = data.AREATYPE.astype('category')

In [92]:
data.RURAL = data.RURAL.astype('category')

In [93]:
data.ELEMENT = data.ELEMENT.astype('category')

In [94]:
data.SUB_CHANNEL = data.SUB_CHANNEL.astype('category')

In [95]:
data.CHANNEL = data.CHANNEL.astype('category')

In [96]:
data.SUB_ELEMENT = data.SUB_ELEMENT.astype('category')

In [97]:
data.SHOPPER_TYPE = data.SHOPPER_TYPE.astype('category')

In [98]:
data.ACTIVE = data.ACTIVE.astype('category')

In [99]:
data.ORDER_STATUS = data.ORDER_STATUS.astype('category')

In [100]:
data.DOC_DATE = pd.to_datetime(data.DOC_DATE)

In [102]:
data.PAYMENT_MODE = data.PAYMENT_MODE.fillna(data.PAYMENT_MODE.value_counts().index[0])

In [103]:
data.PAYMENT_MODE.value_counts(dropna=False).head()

1.0    337100
2.0     18078
Name: PAYMENT_MODE, dtype: int64